version: '3.8'

services:
  sonarqube:
    image: docker.io/sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    restart: unless-stopped

  postgres:
    image: docker.io/library/postgres:17
    container_name: scf-postgres
    ports:
      - "5432:5432"
    networks:
      - scf-network
    environment:
      POSTGRES_DB: finance-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresql123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgres_data:

networks:
  scf-network:
    external: true
